print("heyy, wanna do some additions?")
a = int( input("Write a random number: ") )
b = int( input("Write another random number: ") )
print(f"The addition of {a} + {b} = {a+b}")
print("")
print("heyy, wanna do some multiplications?")
a = int( input("Write a random number: ") )
b = int( input("Write another random number: ") )
print(f"The multiplication of {a} x {b} = {a*b}")
print("")
print("heyy, wanna do some subtractions?")
a = int( input("Write a random number: ") )
b = int( input("Write another random number: ") )
print(f"The subtraction of {a} - {b} = {a-b}")
print("")
print("heyy, wanna do some divisons?")
a = int( input("Write a random number: ") )
b = int( input("Write another random number: ") )
print(f"The divison of {a} ÷ {b} = {a/b}")